@api = http://localhost:3000
POST  {{api}}/productos/login
Content-Type: application/json

{
    "user": "naranita",
    "pass": "conrad"
}

###

POST  {{api}}/productos
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibmFyYW5pdGEiLCJpYXQiOjE3MTIzNDk3MTd9.UmpGyNbvHaBrmNWYey55PAz-T9NLGv2tIA_-Lw6Mu48

{
}

###

POST {{api}}/productos
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibmFyYW5pdGEiLCJpYXQiOjE3MTIzNDk3MTd9.UmpGyNbvHaBrmNWYey55PAz-T9NLGv2tIA_-Lw6Mu48

###
GET {{api}}/imagen/58

### 
POST http://localhost:1000/
Content-Type: application/json

{
    "email":"mi@email.com",
    "password":"minombre"
}


