@port=3001
POST http://localhost:{{port}}/venta
Content-Type: application/json

{
    "venta": {

    },
    "listaProductos": [
        {"existenciaId": 1, "cantidad": 2},
        {"existenciaId": 2, "cantidad": 2}
    ]
}

###

POST http://localhost:{{port}}/venta
Content-Type: application/json

{
    "venta": {
        "esCredito": true
    },
    "listaProductos": [
        {"existenciaId": 1, "cantidad": 2},
        {"existenciaId": 2, "cantidad": 2}
    ]
}
###
PATCH  http://localhost:{{port}}/venta/id
Content-Type: application/json

{
    "venta": {
        "esCredito": true
    },
    "listaProductos": [
        {"existenciaId": 1, "cantidad": 2},
        {"existenciaId": 2, "cantidad": 2}
    ]
}

###
GET http://localhost:{{port}}/venta